name: airpol
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.8.0
  google_fonts: ^4.0.3
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  liquid_progress_indicator: ^0.4.0
  shared_preferences: ^2.1.0
  file_picker: ^5.2.6
  firebase_database: ^10.2.1

dev_dependencies: 
  build_runner: ^2.1.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/LogoPolinema.png

